### ISSUE TITLE
Support members of  interfaces or abstract classes

### ISSUE THREAD

**Issue by Yannick86** [hazzik/DelegateDecompiler#50]
Hey guys,

I'm trying to make use of your API in one of our new projects, but I'm struggling to get everything to work. I can make use of it when the entity has a property which isn't an override or comes from an interface.

Could somebody show me an example with an abstract BaseEntity class which implements an interface. This interface must have 1 simple String property. The BaseEntity implements the String property as abstract.

A last class comes into play which inherits from BaseEntity and thus overrides the String property which returns a concat of 2 other properties.

Imho this isn't complicated, but I keep getting errors at runtime saying that Linq doesn't know the property....again to be clear: I don't have this with regular computed properties which aren't coming from an inherit or implement.

**Comment by mwillebrands** [comment]
Can you post a sample of a testcase which results in problems?

**Comment by hazzik** [comment]
I can confirm that this is a bug.

**Comment by hugoisaac** [comment]
I think I'm having this issue too. Is there a known workaround?

I have an IStudentForm interface that implements another IForm interface:

```csharp
public interface IStudentForm : IForm
    {
        int StudentId { get; set; }
    }

public interface IForm
    {
        // Each form uses a different name for the ID column/property. So, FormId must be implemented
        // as a computed property that uses the real ID property internally.
        int FormId { get; }
        string SaveBy { get; set; }
        DateTime? SaveDate { get; set; }
        bool Submitted { get; set; }
        string SubmitBy { get; set; }
        DateTime? SubmitDate { get; set; }
        bool IsArchive { get; set; }
    }
```

Then I have an entity that implements the FormId as a computed property:

```csharp
[Table(name: "CumulativeRecords", Schema = "forms")]
    public class CumulativeRecord : IStudentForm
    {
        [Key]
        public int CumulativeRecordId { get; set; }
        
        [NotMapped]
        [Computed]
        public int FormId
        {
            get { return CumulativeRecordId; }
        }

        /* Other properties here... */
}
```

Then I have a generic method that relies on the FormId computed property:

```csharp
public static TStudentForm LastSubmitted<TStudentForm>(this IQueryable<TStudentForm> source, int studentId) where TStudentForm : class, IStudentForm
        {
            var studentForm = source
                .OrderByDescending(f => f.SubmitDate)
                .ThenByDescending(f => f.FormId)
                .Decompile()
                .FirstOrDefault(f => f.StudentId == studentId && f.Submitted);

            return studentForm;
        }
```

This is not working and I'm getting the regular error as if I wasn't using DelegateDecompiler: "The specified type member 'FormId' is not supported in LINQ to Entities. Only initializers, entity members, and entity navigation properties are supported."

I have debugged DelegateDecompiler code and the problem seems to be that it is looking for the [Computed] attribute in IForm and not in CumulativeRecord when figuring out if it should decompile the expression. So, it seems it should use reflection over the concrete type, and not the interface. If I decorate IForm.FormId with [Computed] it tries to decompile, but it fails in some place where it calls MethodBase.GetMethodBody() because that returns null for interfaces.

**Comment by hazzik** [comment]
@hugoisaac is it still failing? I could not reproduce your case with a test. Can you submit a failing test as a pull request?

**Comment by hugoisaac** [comment]
@hazzik I couldn't get it working. After trying with 2 or 3 different libraries (including DelegateDecompiler) I couldn't make the computed property work. From what I saw the problem had to do with the property being in an interface. At the end I had to use a different approach with System.Linq.Dynamic.

**Comment by Xoroles** [comment]
Hi, 

I have the same Problem and Work actually on a Fork. I think with some Improvements in the Configuration.cs i can produce a fix, so you must Write on this specific issuer his own configuration and overwrite a Method to get the MethodInfo from the concrete Type. Because you have at this point the MemberInfo of the Interface Property.

**Comment by bouskdav** [comment]
+1 from me - I have the same issue - have multiple tables that implement `IUniversalInvoice` interface with some properties. Then when I try to execute lambda `Expression<Func<IUniversalInvoice, bool>>` on `IQueryable<IUniversalInvoice>` that includes some properties from interface (e. g. `c => c.UIInvoiceNumber.Contains(q) || c.UISymbolVar.Contains(q)` ) it throws the same exception as above.
