### ISSUE TITLE
MemberInitExpression is not created when decompiling from a MethodInfo or Delegate

### ISSUE THREAD

**Issue by ykosbie** [hazzik/DelegateDecompiler#83]
When you decompile from an IQueryable which contains a MemberInitExpression, that expression is preserved.  However, when you decompile from a MethodInfo or a Delegate which creates an object with the object initializer syntax, no member init expression is created.

```
void Main()
{
    Expression<Func<foo, bar>> e = x => new bar {
        t = x.t
    };
    Func<foo, bar> f = x => new bar {
        t = x.t
    };

    new List<foo>().AsQueryable().Select(e).Decompile().Expression.Dump();
    f.Decompile().Dump();
    this.GetType().GetMethod("MakeBar").Decompile().Dump();
}

public bar MakeBar(foo f) {
    return new bar {
        t = f.t
    };
}

public class foo {
    public bool t {get;set;}
}

public class bar {
    public bool t {get;set;}
}
```

**Comment by morgen2009** [comment]
Thanks for nice weekend :) The sample from the post works.

The *Processor* class handled setters as *void* methods and returned constructor, because it was the last resulting method. Also, IL instructions for anonymouns functions contain reference to the context (as ConstantExpression) instead of reference to *this* (as ParameterExpression). This expression should be excluded from expression parameters. See pull-request

I do not understand how to get correct reference to the context and write currently *NULL*. So far, you don't use variables from outer scope, this works well. I would be thankful for any info.

**Comment by morgen2009** [comment]
As I undestand `f.Decompile()` doesn't create `Expression<Func<foo, bar>>`, but `Expression<Func<context, foo, bar>>`. The **context** stands for instance of class (methods) or for instance of anonymous class (lambda) and should be later replaced by the actual value. In native expression tree the value ist already included as `ConstantExpression`. In IL instructions, this is just parameter like `$this`.

Are there any API to quickly inject the reference to the context in `Expression` after `Decompile()`?

**Comment by hazzik** [comment]
@morgen2009 could you please create an issue for your last question?
