### ISSUE TITLE
DateTime in linq queries

### ISSUE THREAD

**Issue by Unders0n** [hazzik/DelegateDecompiler#89]
Hello, have you experinced trouble with DateTime? Discussed here: http://stackoverflow.com/questions/17371798/how-to-use-dateadd-over-column-in-linq-dateadd-is-not-recognized-by-linq

Everybody sujjests to use DbFunctions.AddYears() but its decrease all profit of linq - its interoperability, you cant use it in linq2objects or to test it locally. So that i was thinking is that we can leave regular .addYears() and then our .Decompile can change it to DbFunctions on runtime? What do you think?

**Comment by NetMastr5** [comment]
A workaround to this problem is to use another library that allows you to create your own db function mapped methods.  I use this to map many different db functions (custom and builtin).  I do this in conjunction with delegate decompiler.  The library I use for this is https://weblogs.asp.net/Dixin/EntityFramework.Functions

**Comment by Unders0n** [comment]
@NetMastr5 I think the "Scalar-valued function, composable" from examples is what we need, but i don't get it, they just added throwing of NonSupported error to it ?

**Comment by NetMastr5** [comment]
Yes, they are just placeholders of where the DB functions should be.  When the Entity Framework's data provider parses the expression tree to generate the query, it generates the text you specify in the stub function's scalar valued attribute, because the library registers those mappings.  Now there is an oddity that I have run across for builtin functions in Oracle that looks like a bug in Oracle's EF provider.  If you map to a function that returns a true/false result, such as the LIKE comparer, the query generated tries to compare the result to 1 instead of taking it as is.  The library sets the correct return type, but oracle still thinks number. You can work around this by wrapping those in a custom function that returns 0/1 in place of the true/false.

**Comment by hazzik** [comment]
I think this is out of scope of DD.
